# Generated by Django 4.0.4 on 2022-05-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
